// Simulated GraphRAG — pre-built global summary of the company structure.
// In a real system this summary would be generated by an LLM over the full graph.

const COMPANY_SUMMARY = `
The company has a flat three-level hierarchy with 6 employees across two departments.

LEADERSHIP
- Anna (CEO) sits at the top and oversees the entire organization.
- She has two direct reports: Jan (CTO) and Ewa (CFO).

TECHNOLOGY DEPARTMENT (led by Jan, CTO)
- Responsible for all software development and technical infrastructure.
- Jan manages two developers: Piotr and Maria.
- Piotr focuses on backend development; Maria focuses on front-end.

FINANCE DEPARTMENT (led by Ewa, CFO)
- Responsible for budgeting, financial planning, and accounting.
- Ewa manages one accountant: Tomasz.
- Tomasz handles day-to-day accounting operations and payroll.

OVERALL STRUCTURE
- 1 CEO (Anna)
- 2 department heads (Jan, Ewa)
- 3 individual contributors (Piotr, Maria, Tomasz)
- All decisions flow through Anna; departments operate independently.
`.trim();

export function query(_question: string): string {
  return COMPANY_SUMMARY;
}
